---
# tasks file for pre-req

- name: garantindo os pacotes basicos instalados
  package:
   name:
    - docker-ce
    - nginx
    - python-pip

- name: garantindo o docker-py
  pip:
   name: docker-py

- name: garantindo os servicos
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker
