- name: instalando pacotes
  package:
   name: "{{item}}"
  with_items:
    - docker-ce
    - nginx
    - python-pip

- name: garantindo o docker-py
  pip:
   name: docker-py

- name: garantindo os servicos docker e nginx rodando
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker
